
spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.qkgor.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=Cluster0
  application:
    name: webflux-course
